config/routes.rb
Rails.application.routes.draw do
  get "registrations/new"
  get "registrations/create"
  resource :registration, only: [ :new, :create ]
  resource :session
  resources :passwords, param: :token
  root "chats#index"
  resources :chats, only: [ :index, :create, :show, :destroy ], param: :uuid do
    member do
      get "delete_modal"
    end
  end
  get "/auth/google_oauth2/callback", to: "sessions#google"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_auth_footer.html.erb
<div class="flex justify-center gap-4 mt-4 text-xs text-zinc-500 dark:text-zinc-400">
  <a href="/terms" class="hover:underline">利用規約</a>
  <span>|</span>
  <a href="/privacy" class="hover:underline">プライバシーポリシー</a>
</div>

app/views/shared/_chat_header.html.erb
<header class="flex sticky top-0 bg-background py-1.5 justify-between items-center px-2 md:px-2 gap-2 h-16">
  <div class="flex">
    <button
      class="hover:bg-zinc-200 dark:hover:bg-zinc-700 h-10 rounded-lg px-2"
      data-action="click->sidebar#toggle"
      data-sidebar-target="openButton"
    >
      <%= icon "sidebar" %>
    </button>
    <%= link_to :root, class: "hover:bg-zinc-200 inline-flex items-center justify-center dark:hover:bg-zinc-700 h-10 rounded-lg px-2 focus:outline-none" do %>
      <%= icon "edit" %>
    <% end %>
    <div data-controller="chat-model dropdown" class="relative inline-block">
      <div>
        <button
          type="button"
          class="inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-sm"
          aria-haspopup="true"
          data-action="click->dropdown#toggle click@window->dropdown#hide"
        >
          <span data-chat-model-target="selectedModel">gemini-2.0-flash</span>
          <%= icon "down" %>
        </button>
      </div>
      <div
        data-dropdown-target="menu"
        class="hidden absolute z-10 mt-2 w-56 origin-top-right rounded-md shadow-lg ring-1 dark:bg-zinc-800 ring-black/5 focus:outline-hidden opacity-100">
        <div class="py-1" role="none">
          <% Chat::MODELS.each do |model| %>
            <button data-action="click->chat-model#select click->dropdown#toggle" data-model="<%= model[:id] %>" class="gap-4 group/item flex justify-between items-center p-2">
              <div class="flex flex-col gap-1 items-start">
                <div><%= model[:name] %></div>
                <div class="text-xs text-muted-foreground text-zinc-500 text-left">
                  <%= model[:description] %>
                </div>
              </div>
              <button data-model="<% model[:id] %>" data-chat-model-target="checked">
                <%= icon "check" %>
              </button>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="relative inline-block text-left" data-controller="dropdown">
    <div>
      <button
        type="button"
        class="inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-sm"
        id="menu-button"
        data-action="click->dropdown#toggle click@window->dropdown#hide"
      >
        <div
          data-controller="react"
          data-react-component="BoringAvatar"
          data-props="<%= { name: Current.session.user.email_address }.to_json %>">
        </div>
      </button>
    </div>
    <div data-dropdown-target="menu" class="hidden absolute right-0 z-100 mt-2 w-56 origin-top-right rounded-md shadow-lg dark:bg-zinc-800 ring-black/5">
      <div class="py-1" role="none">
        <button data-controller="color-mode" data-action="click->color-mode#toggle" class="gap-4 group/item flex justify-between items-center p-2">
          <span data-color-mode-target="button"></span>
        </button>
        <%= link_to "ログアウト", session_path, data: { turbo_method: :delete }, class: "block px-4 py-2 text-sm" %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_google_login.html.erb
<div class="flex items-center justify-center">
  <div class="h-px px-4 sm:px-16 bg-zinc-200 dark:bg-zinc-600"></div>
  <span class="mx-4 my-2 text-sm text-zinc-500 dark:text-zinc-400 writing-mode-vertical-rl text-orientation-upright">
    または
  </span>
  <div class="h-px px-4 sm:px-16 bg-zinc-200 dark:bg-zinc-600"></div>
</div>

<div class="flex flex-col gap-4 px-4 sm:px-16">
  <%= link_to "/auth/google_oauth2", class: "inline-flex items-center justify-center gap-2 border border-zinc-200 rounded-md text-sm cursor-pointer font-medium hover:bg-zinc-200 dark:hover:bg-zinc-800 h-10 px-4 py-2" do %>
    <%= icon "google" %>
    Google で続行
  <% end %>
</div>