config/routes.rb
Rails.application.routes.draw do
  get "registrations/new"
  get "registrations/create"
  resource :registration, only: [ :new, :create ]
  resource :session
  resources :passwords, param: :token
  root "chats#index"
  resources :chats, only: [ :index, :create, :show, :destroy ], param: :uuid do
    member do
      get "delete_modal"
    end
  end
  get "/auth/google_oauth2/callback", to: "sessions#google"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :uuid, presence: true, uniqueness: true

  validate :uuid_format

  MODELS = [
    {
      provider: "gemini",
      id: "gemini-2.0-flash",
      name: "gemini-2.0-flash",
      description: "次世代の機能と強化された機能を提供",
      access_token: Rails.application.credentials.dig(:gemini, :api_key),
      uri_base: "https://generativelanguage.googleapis.com/v1beta/openai/"
    },
    {
      provider: "openai",
      id: "gpt-4o",
      name: "gpt-4o",
      description: "汎用性と知能に優れたフラッグシップモデル",
      access_token: Rails.application.credentials.dig(:openai, :api_key),
      uri_base: nil # 指定不要
    }
  ]

  private

  UUID_REGEXP = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/i

  def uuid_format
    unless uuid =~ UUID_REGEXP
      errors.add(:uuid, "must be a valid UUID format")
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include ActionController::Live

  def index
  end

  def show
    @chat = Current.session.user.chats.find_by!(uuid: params[:uuid])

    respond_to do |format|
      format.html { render template: "chats/index" }
      format.turbo_stream
    end
  end

  def create
    set_streaming_headers
    sse = SSE.new(response.stream, event: "message")
    chat_model = Chat::MODELS.index_by { |m| m[:id] }[params[:chat_model]]
    unless chat_model
      raise "Invalid model specified"
    end
    client = OpenAI::Client.new(chat_model.slice(:access_token, :uri_base))

    begin
      content = stream_chat_response(client, sse, chat_model)
      chat = Chat.find_or_initialize_by(uuid: params[:uuid]) do |chat|
        chat.user = Current.session.user
        chat.title = generate_title(client, chat_model)
      end
      Rails.logger.debug("chat: #{chat.inspect}")
      if chat.user != Current.session.user
        raise "User mismatch"
      end
      chat.messages.build(role: "user", content: params[:prompt])
      chat.messages.build(role: "assistant", content: content)
      chat.save!
    rescue ActiveRecord::RecordInvalid => e
      Rails.logger.error("Failed to save chat: #{e.message}")
    ensure
      sse.close
    end
  end

  def delete_modal
    @chat = Current.session.user.chats.find_by!(uuid: params[:uuid])
    respond_to do |format|
      format.turbo_stream { render "chats/delete_modal" }
    end
  end

  def destroy
    @chat = Current.session.user.chats.find_by!(uuid: params[:uuid])
    @chat.destroy
    redirect_to chats_path, notice: "チャットを削除しました"
  end

  private

  def set_streaming_headers
    response.headers["Content-Type"]  = "text/event-stream"
    response.headers["Last-Modified"] = Time.now.httpdate
    response.headers.delete("Content-Encoding")
    response.headers.delete("Content-Length")
  end

  def stream_chat_response(client, sse, chat_model)
    full_content = ""

    client.chat(
      parameters: {
        model: chat_model[:id],
        messages: [ { role: "user", content: params[:prompt] } ],
        stream: proc do |chunk|
          content = chunk.dig("choices", 0, "delta", "content")
          if content
            sse.write({ message: content })
            full_content += content
          end
        end
      }
    )
    full_content
  end

  def generate_title(client, chat_model)
    system_prompt = <<~SYSTEM_PROMPT
      - ユーザーが会話を始める最初のメッセージに基づいて、短いタイトルを生成します
      - タイトルは80文字以内に収めてください
      - タイトルはユーザーのメッセージの要約であるべきです
      - 引用符やコロンは使用しないでください
      - タイトルは日本語で生成してください
    SYSTEM_PROMPT
    client.chat(
      parameters: {
        model: chat_model[:id],
        messages: [
          { role: "system", content: system_prompt },
          { role: "user", content: "Generate a title for the following chat: #{params[:prompt]}" }
        ]
      }
    ).dig("choices", 0, "message", "content").chomp
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_link.html.erb
<div class="relative" data-controller="dropdown">
  <div class="group rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-800 h-9 text-sm relative">
    <div class="flex justify-between items-center px-1">
      <%= link_to chat_path(uuid: chat.uuid), class: "flex items-center gap-2 p-2" do %>
        <div class="relative grow overflow-hidden whitespace-nowrap">
          <p class="truncate w-[150px]"><%= chat.title || chat.uuid %></p>
        </div>
      <% end %>
      <button
        data-action="click->dropdown#toggle click@window->dropdown#hide"
      >
        <%= icon "ellipsis" %>
      </button>
    </div>
    <div data-dropdown-target="menu" class="hidden absolute z-30 mt-2 w-32 right-0 rounded-md bg-white dark:bg-zinc-800 shadow-lg ring-1 ring-black/5 focus:outline-hidden">
      <div class="py-1" role="none" data-action="click->dropdown#toggle">
        <%= link_to delete_modal_chat_path(uuid: chat.uuid), data: { turbo_frame: :modal, turbo_stream: true }, class: "gap-4 group/item flex justify-between items-center p-2" do %>
          <%= icon "trash" %>
          <div class="flex flex-col gap-1 items-start text-red-400">
            <div>削除</div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chats/delete_modal.turbo_stream.erb
<%= turbo_stream.show_modal do %>
  <dialog id="delete_chat_modal">
    <div class="fixed inset-0 z-50">
      <div class="fixed inset-0 bg-black/50 transition-opacity"></div>
      <div class="fixed inset-0 z-50 w-screen overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <div class="relative transform overflow-hidden rounded-lg bg-white dark:bg-zinc-800 px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-6">
            <div class="sm:flex sm:items-start">
              <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                <h3 class="text-base font-semibold" id="modal-title">
                  チャットを削除しますか？
                </h3>
                <div class="mt-2">
                  <p class="text-sm text-zinc-600 dark:text-zinc-300">
                    <span class="font-bold"><%= @chat.title %></span>を削除します。
                  </p>
                </div>
              </div>
            </div>
            <div class="mt-5 sm:mt-4 flex gap-2 justify-end">
              <%= link_to chat_path(uuid: @chat.uuid), data: { turbo_method: :delete, turbo_frame: "_top" }, class: "mt-3 inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-red-500 sm:ml-3 sm:w-auto" do %>
                削除する
              <% end %>
              <form method="dialog">
                <button type="submit" class="mt-3 inline-flex w-full justify-center rounded-md bg-zinc-200 px-3 py-2 text-sm font-semibold text-zinc-800 shadow-xs hover:bg-zinc-300 sm:ml-3 sm:w-auto">
                  キャンセルする
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </dialog>
<% end %>

app/views/chats/index.html.erb
<div data-controller="sidebar" class="group/sidebar-wrapper flex min-h-svh w-full">

  <div data-sidebar-target="sidebar" class="z-20 dark:bg-black bg-white shrink-0 w-64 h-screen overflow-y-auto">
    <div class="h-full w-64">
      <div class="flex h-full min-h-0 flex-col">
        <div class="relative h-full w-full flex-1 items-start border-r border-zinc-700">
          <h2 class="sr-only">チャット履歴</h2>
          <nav class="flex h-full w-full flex-col pl-3">
            <div class="flex justify-between h-16 items-center pr-3">
              <button
                class="hover:bg-zinc-200 dark:hover:bg-zinc-700 h-10 rounded-lg px-2"
                aria-label="サイドバーを閉じる"
                data-action="click->sidebar#toggle"
                data-sidebar-target="toggleButton"
              >
                <%= icon "sidebar" %>
              </button>
              <%= link_to :root, class: "hover:bg-zinc-200 inline-flex items-center justify-center dark:hover:bg-zinc-700 h-10 rounded-lg px-2 focus:outline-none" do %>
                <%= icon "edit" %>
              <% end %>
            </div>
            <div class="flex-col flex-1 transition-opacity duration-500 relative pr-3 overflow-y-auto">
              <div id="sidebar" class="group/sidebar">
                <div class="flex flex-col gap-2 text-sm">
                  <div>
                    <div class="relative first:mt-0 last:mb-5">
                      <div class="relative flex w-full min-w-0 flex-col p-2">
                        <div class="w-full text-sm">
                          <div class="flex w-full min-w-0 flex-col gap-1">
                            <div class="flex flex-col gap-2">
                              <%= turbo_frame_tag "chat_links" %>
                              <% Current.session.user.chats.order(created_at: :desc).each do |chat| %>
                                <%= render partial: "chats/link", locals: { chat: chat } %>
                              <% end %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <div class="relative flex min-h-svh flex-1 flex-col" data-controller="chat">
    <div class="flex flex-col min-w-0 h-dvh bg-background">
      <%= render partial: "shared/chat_header" %>
      <div class="overflow-y-scroll min-w-0 flex-1">
        <div class="flex flex-col pt-4 gap-6">
          <% if (@chat&.messages || []).empty? %>
            <div data-chat-target="greeting" class="max-w-3xl mx-auto flex flex-1 items-center min-h-[60vh]">
              <div class="text-xl md:text-2xl font-semibold text-left mx-0">
                お手伝いできることはありますか？
              </div>
            </div>
          <% end %>
          <% (@chat&.messages || []).each do |message| %>
            <div class="w-full mx-auto max-w-3xl px-4 group/message" data-role="<%= message[:role] %>">
              <div class="flex gap-4 w-full group-data-[role=user]/message:ml-auto group-data-[role=user]/message:max-w-2xl group-data-[role=user]/message:w-fit">
                <div class="flex flex-col gap-4 w-full">
                  <div class="flex flex-row gap-2 items-start">
                    <div class="flex flex-col gap-4 group-data-[role=user]/message:bg-zinc-200 group-data-[role=user]/message:dark:bg-zinc-700 group-data-[role=user]/message:dark:text-white group-data-[role=user]/message:text-black group-data-[role=user]/message:px-3 group-data-[role=user]/message:py-2 group-data-[role=user]/message:rounded-xl">
                      <% if message.role == "assistant" %>
                        <div data-controller="markdown">
                          <%= message.content %>
                        </div>
                      <% else %>
                        <%= message.content %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="flex flex-col pt-4 gap-6" data-chat-target="conversation"></div>
        <div class="shrink-0 min-w-[24px] min-h-[24px]" data-chat-target="scroll"></div>
      </div>
      <%= form_with data: { action: "chat#generateResponse" }, class: "flex mx-auto px-4 bg-background pb-4 md:pb-6 gap-2 w-full md:max-w-3xl" do |form| %>
        <input type="hidden" name="authenticity_token" value="[YOUR_CSRF_TOKEN_HERE]">
        <div class="relative w-full flex flex-col gap-4">
          <%= form.text_area :input, data: { chat_target: "prompt" }, placeholder: "質問してみましょう", class: "flex w-full border border-input bg-background px-3 py-2 md:text-sm resize-none rounded-2xl bg-muted pb-10 border-zinc-300 dark:border-zinc-700", rows: 2, autofocus: true, id: "input", onkeydown: "if(event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); this.form.requestSubmit(); }" %>

          <div class="absolute bottom-0 right-0 p-2 w-fit flex flex-row justify-end">
            <button type="submit" class="rounded-full p-1.5 h-fit border dark:border-zinc-600">
              <%= icon "arrowup" %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<template id="chat-message">
  <div class="w-full mx-auto max-w-3xl px-4 group/message">
    <div class="flex gap-4 w-full group-data-[role=user]/message:ml-auto group-data-[role=user]/message:max-w-2xl group-data-[role=user]/message:w-fit">
      <div class="flex flex-col gap-4 w-full">
        <div class="flex flex-row gap-2 items-start">
          <div class=" flex flex-col gap-4 group-data-[role=user]/message:bg-zinc-200 group-data-[role=user]/message:dark:bg-zinc-700 group-data-[role=user]/message:dark:text-white group-data-[role=user]/message:text-black group-data-[role=user]/message:px-3 group-data-[role=user]/message:py-2 group-data-[role=user]/message:rounded-xl ">
            <div class="message"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

app/views/chats/show.turbo_stream.erb
<%= turbo_stream.prepend "chat_links" do %>
  <%= render "chats/link", chat: @chat %>
<% end %>